server:
  port: 10002

tcp:
  port: 28888

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

spring:
  #MQTT配置信息
  mqtt:
    #MQTT服务端地址，端口默认为1883，如果有多个，用逗号隔开
    url: tcp://182.85.254.44:1883
    #用户名
    username: admin
    #密码
    password: 123456
    #客户端id（不能重复）
    client:
      id: consumer-id
    #MQTT默认的消息推送主题，实际可在调用接口时指定
    default:
      topic: topic

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 30s
      database: 0
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
          max-wait: -1ms
  application:
    name: system-user-web
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: woshifangziyuan1
    url: jdbc:mysql://ac.aaarfyh.com:3306/kantboot1?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
  jpa:
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibenate:
        format_sql: true
        enable_lazy_load_no_trans: true
        bytecode:
          use_reflection_optimizer: false
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
