server:
  port: 10002

tcp:
  port: 28888

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 30s
      database: 0
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
          max-wait: -1ms
  application:
    name: system-user-web
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: woshifangziyuan1
    url: jdbc:mysql://ac.aaarfyh.com:3306/kantboot1?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
  jpa:
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibenate:
        format_sql: true
        enable_lazy_load_no_trans: true
        bytecode:
          use_reflection_optimizer: false
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
